### ISSUE TITLE
Missing characters

### ISSUE THREAD

**Issue by TonyVie** [marecl/HPDL1414#1]
Hi, 

First, thanks for your work !

I have an issue: first character is missing (due to offset), and third character is blank.

For example: 
-if I want "ABCD", it prints "B D ".
-if I want "1234", it prints "2 4 ".

Any Idea ?
Thanks !

**Comment by marecl** [comment]
Hi. Have you checked the wiring? Breadboards tend to have poor contact.
Please let me know if you have the same issue with example sketches.

**Comment by TonyVie** [comment]
Ok, I was trying with an ESP8266. I checked on an arduino pro miro and everything is fine.
I'll double check my pinout with the esp.

**Comment by TonyVie** [comment]
It works (both arduino, esp, dual screen).
Thanks again for your work :)
